/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IngressSpecAllOfDefaultBackendAllOfResource from './IngressSpecAllOfDefaultBackendAllOfResource';
import IngressSpecAllOfDefaultBackendAllOfService from './IngressSpecAllOfDefaultBackendAllOfService';

/**
 * The IngressSpecAllOfDefaultBackend model module.
 * @module model/IngressSpecAllOfDefaultBackend
 * @version 1.0.0
 */
class IngressSpecAllOfDefaultBackend {
    /**
     * Constructs a new <code>IngressSpecAllOfDefaultBackend</code>.
     * defaultBackend is the backend that should handle requests that don&#39;t match any rule. If Rules are not specified, DefaultBackend must be specified. If DefaultBackend is not set, the handling of requests that do not match any of the rules will be up to the Ingress controller.
     * @alias module:model/IngressSpecAllOfDefaultBackend
     */
    constructor() { 
        
        IngressSpecAllOfDefaultBackend.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IngressSpecAllOfDefaultBackend</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngressSpecAllOfDefaultBackend} obj Optional instance to populate.
     * @return {module:model/IngressSpecAllOfDefaultBackend} The populated <code>IngressSpecAllOfDefaultBackend</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngressSpecAllOfDefaultBackend();

            if (data.hasOwnProperty('resource')) {
                obj['resource'] = IngressSpecAllOfDefaultBackendAllOfResource.constructFromObject(data['resource']);
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = IngressSpecAllOfDefaultBackendAllOfService.constructFromObject(data['service']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IngressSpecAllOfDefaultBackend</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IngressSpecAllOfDefaultBackend</code>.
     */
    static validateJSON(data) {
        // validate the optional field `resource`
        if (data['resource']) { // data not null
          IngressSpecAllOfDefaultBackendAllOfResource.validateJSON(data['resource']);
        }
        // validate the optional field `service`
        if (data['service']) { // data not null
          IngressSpecAllOfDefaultBackendAllOfService.validateJSON(data['service']);
        }

        return true;
    }


}



/**
 * @member {module:model/IngressSpecAllOfDefaultBackendAllOfResource} resource
 */
IngressSpecAllOfDefaultBackend.prototype['resource'] = undefined;

/**
 * @member {module:model/IngressSpecAllOfDefaultBackendAllOfService} service
 */
IngressSpecAllOfDefaultBackend.prototype['service'] = undefined;






export default IngressSpecAllOfDefaultBackend;

