/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IngressStatusAllOfLoadBalancerAllOfIngressInner from './IngressStatusAllOfLoadBalancerAllOfIngressInner';

/**
 * The IngressStatusAllOfLoadBalancer model module.
 * @module model/IngressStatusAllOfLoadBalancer
 * @version 1.0.0
 */
class IngressStatusAllOfLoadBalancer {
    /**
     * Constructs a new <code>IngressStatusAllOfLoadBalancer</code>.
     * loadBalancer contains the current status of the load-balancer.
     * @alias module:model/IngressStatusAllOfLoadBalancer
     */
    constructor() { 
        
        IngressStatusAllOfLoadBalancer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IngressStatusAllOfLoadBalancer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngressStatusAllOfLoadBalancer} obj Optional instance to populate.
     * @return {module:model/IngressStatusAllOfLoadBalancer} The populated <code>IngressStatusAllOfLoadBalancer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngressStatusAllOfLoadBalancer();

            if (data.hasOwnProperty('ingress')) {
                obj['ingress'] = ApiClient.convertToType(data['ingress'], [IngressStatusAllOfLoadBalancerAllOfIngressInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IngressStatusAllOfLoadBalancer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IngressStatusAllOfLoadBalancer</code>.
     */
    static validateJSON(data) {
        if (data['ingress']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ingress'])) {
                throw new Error("Expected the field `ingress` to be an array in the JSON data but got " + data['ingress']);
            }
            // validate the optional field `ingress` (array)
            for (const item of data['ingress']) {
                IngressStatusAllOfLoadBalancerAllOfIngressInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * ingress is a list containing ingress points for the load-balancer.
 * @member {Array.<module:model/IngressStatusAllOfLoadBalancerAllOfIngressInner>} ingress
 */
IngressStatusAllOfLoadBalancer.prototype['ingress'] = undefined;






export default IngressStatusAllOfLoadBalancer;

