/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IngressStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner from './IngressStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner';

/**
 * The IngressStatusAllOfLoadBalancerAllOfIngressInner model module.
 * @module model/IngressStatusAllOfLoadBalancerAllOfIngressInner
 * @version 1.0.0
 */
class IngressStatusAllOfLoadBalancerAllOfIngressInner {
    /**
     * Constructs a new <code>IngressStatusAllOfLoadBalancerAllOfIngressInner</code>.
     * @alias module:model/IngressStatusAllOfLoadBalancerAllOfIngressInner
     */
    constructor() { 
        
        IngressStatusAllOfLoadBalancerAllOfIngressInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IngressStatusAllOfLoadBalancerAllOfIngressInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngressStatusAllOfLoadBalancerAllOfIngressInner} obj Optional instance to populate.
     * @return {module:model/IngressStatusAllOfLoadBalancerAllOfIngressInner} The populated <code>IngressStatusAllOfLoadBalancerAllOfIngressInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngressStatusAllOfLoadBalancerAllOfIngressInner();

            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
            if (data.hasOwnProperty('ip')) {
                obj['ip'] = ApiClient.convertToType(data['ip'], 'String');
            }
            if (data.hasOwnProperty('ports')) {
                obj['ports'] = ApiClient.convertToType(data['ports'], [IngressStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IngressStatusAllOfLoadBalancerAllOfIngressInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IngressStatusAllOfLoadBalancerAllOfIngressInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['hostname'] && !(typeof data['hostname'] === 'string' || data['hostname'] instanceof String)) {
            throw new Error("Expected the field `hostname` to be a primitive type in the JSON string but got " + data['hostname']);
        }
        // ensure the json data is a string
        if (data['ip'] && !(typeof data['ip'] === 'string' || data['ip'] instanceof String)) {
            throw new Error("Expected the field `ip` to be a primitive type in the JSON string but got " + data['ip']);
        }
        if (data['ports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ports'])) {
                throw new Error("Expected the field `ports` to be an array in the JSON data but got " + data['ports']);
            }
            // validate the optional field `ports` (array)
            for (const item of data['ports']) {
                IngressStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * hostname is set for load-balancer ingress points that are DNS based.
 * @member {String} hostname
 */
IngressStatusAllOfLoadBalancerAllOfIngressInner.prototype['hostname'] = undefined;

/**
 * ip is set for load-balancer ingress points that are IP based.
 * @member {String} ip
 */
IngressStatusAllOfLoadBalancerAllOfIngressInner.prototype['ip'] = undefined;

/**
 * ports provides information about the ports exposed by this LoadBalancer.
 * @member {Array.<module:model/IngressStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner>} ports
 */
IngressStatusAllOfLoadBalancerAllOfIngressInner.prototype['ports'] = undefined;






export default IngressStatusAllOfLoadBalancerAllOfIngressInner;

