/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IngressStatusAllOfLoadBalancer from './IngressStatusAllOfLoadBalancer';

/**
 * The IngressStatus model module.
 * @module model/IngressStatus
 * @version 1.0.0
 */
class IngressStatus {
    /**
     * Constructs a new <code>IngressStatus</code>.
     * status is the current state of the Ingress. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
     * @alias module:model/IngressStatus
     */
    constructor() { 
        
        IngressStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IngressStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IngressStatus} obj Optional instance to populate.
     * @return {module:model/IngressStatus} The populated <code>IngressStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IngressStatus();

            if (data.hasOwnProperty('loadBalancer')) {
                obj['loadBalancer'] = IngressStatusAllOfLoadBalancer.constructFromObject(data['loadBalancer']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IngressStatus</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IngressStatus</code>.
     */
    static validateJSON(data) {
        // validate the optional field `loadBalancer`
        if (data['loadBalancer']) { // data not null
          IngressStatusAllOfLoadBalancer.validateJSON(data['loadBalancer']);
        }

        return true;
    }


}



/**
 * @member {module:model/IngressStatusAllOfLoadBalancer} loadBalancer
 */
IngressStatus.prototype['loadBalancer'] = undefined;






export default IngressStatus;

