/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner model module.
 * @module model/K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner
 * @version 1.0.0
 */
class K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner {
    /**
     * Constructs a new <code>K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner</code>.
     * @alias module:model/K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner
     * @param port {Number} port is the port number of the ingress port.
     * @param protocol {String} protocol is the protocol of the ingress port. The supported values are: \"TCP\", \"UDP\", \"SCTP\"
     */
    constructor(port, protocol) { 
        
        K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.initialize(this, port, protocol);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, port, protocol) { 
        obj['port'] = port || 0;
        obj['protocol'] = protocol || '';
    }

    /**
     * Constructs a <code>K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner} obj Optional instance to populate.
     * @return {module:model/K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner} The populated <code>K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('protocol')) {
                obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }
        // ensure the json data is a string
        if (data['protocol'] && !(typeof data['protocol'] === 'string' || data['protocol'] instanceof String)) {
            throw new Error("Expected the field `protocol` to be a primitive type in the JSON string but got " + data['protocol']);
        }

        return true;
    }


}

K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.RequiredProperties = ["port", "protocol"];

/**
 * error is to record the problem with the service port The format of the error shall comply with the following rules: - built-in error values shall be specified in this file and those shall use   CamelCase names - cloud provider specific error values must have names that comply with the   format foo.example.com/CamelCase.
 * @member {String} error
 */
K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.prototype['error'] = undefined;

/**
 * port is the port number of the ingress port.
 * @member {Number} port
 * @default 0
 */
K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.prototype['port'] = 0;

/**
 * protocol is the protocol of the ingress port. The supported values are: \"TCP\", \"UDP\", \"SCTP\"
 * @member {String} protocol
 * @default ''
 */
K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner.prototype['protocol'] = '';






export default K8sResourceStatusAllOfLoadBalancerAllOfIngressInnerAllOfPortsInner;

