/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort model module.
 * @module model/K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort
 * @version 1.0.0
 */
class K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort {
    /**
     * Constructs a new <code>K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort</code>.
     * port of the referenced service. A port name or port number is required for a IngressServiceBackend.
     * @alias module:model/K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort
     */
    constructor() { 
        
        K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort} obj Optional instance to populate.
     * @return {module:model/K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort} The populated <code>K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * name is the name of the port on the Service. This is a mutually exclusive setting with \"Number\".
 * @member {String} name
 */
K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort.prototype['name'] = undefined;

/**
 * number is the numerical port number (e.g. 80) on the Service. This is a mutually exclusive setting with \"Name\".
 * @member {Number} number
 */
K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort.prototype['number'] = undefined;






export default K8sResourceSpecAllOfDefaultBackendAllOfServiceAllOfPort;

