/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner model module.
 * @module model/PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner
 * @version 1.0.0
 */
class PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner {
    /**
     * Constructs a new <code>PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner</code>.
     * @alias module:model/PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner
     * @param mountPath {String} MountPath corresponds to the original VolumeMount.
     * @param name {String} Name corresponds to the name of the original VolumeMount.
     */
    constructor(mountPath, name) { 
        
        PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.initialize(this, mountPath, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mountPath, name) { 
        obj['mountPath'] = mountPath || '';
        obj['name'] = name || '';
    }

    /**
     * Constructs a <code>PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner} obj Optional instance to populate.
     * @return {module:model/PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner} The populated <code>PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner();

            if (data.hasOwnProperty('mountPath')) {
                obj['mountPath'] = ApiClient.convertToType(data['mountPath'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('recursiveReadOnly')) {
                obj['recursiveReadOnly'] = ApiClient.convertToType(data['recursiveReadOnly'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['mountPath'] && !(typeof data['mountPath'] === 'string' || data['mountPath'] instanceof String)) {
            throw new Error("Expected the field `mountPath` to be a primitive type in the JSON string but got " + data['mountPath']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['recursiveReadOnly'] && !(typeof data['recursiveReadOnly'] === 'string' || data['recursiveReadOnly'] instanceof String)) {
            throw new Error("Expected the field `recursiveReadOnly` to be a primitive type in the JSON string but got " + data['recursiveReadOnly']);
        }

        return true;
    }


}

PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.RequiredProperties = ["mountPath", "name"];

/**
 * MountPath corresponds to the original VolumeMount.
 * @member {String} mountPath
 * @default ''
 */
PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.prototype['mountPath'] = '';

/**
 * Name corresponds to the name of the original VolumeMount.
 * @member {String} name
 * @default ''
 */
PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.prototype['name'] = '';

/**
 * ReadOnly corresponds to the original VolumeMount.
 * @member {Boolean} readOnly
 */
PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.prototype['readOnly'] = undefined;

/**
 * RecursiveReadOnly must be set to Disabled, Enabled, or unspecified (for non-readonly mounts). An IfPossible value in the original VolumeMount must be translated to Disabled or Enabled, depending on the mount result.
 * @member {String} recursiveReadOnly
 */
PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner.prototype['recursiveReadOnly'] = undefined;






export default PodStatusAllOfContainerStatusesInnerAllOfVolumeMountsInner;

