/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfClusterTrustBundle from './PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfClusterTrustBundle';
import PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap from './PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap';
import PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI from './PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI';
import PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfSecret from './PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfSecret';
import PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfServiceAccountToken from './PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfServiceAccountToken';

/**
 * The PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner</code>.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner
     */
    constructor() { 
        
        PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner} The populated <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner();

            if (data.hasOwnProperty('clusterTrustBundle')) {
                obj['clusterTrustBundle'] = PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfClusterTrustBundle.constructFromObject(data['clusterTrustBundle']);
            }
            if (data.hasOwnProperty('configMap')) {
                obj['configMap'] = PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.constructFromObject(data['configMap']);
            }
            if (data.hasOwnProperty('downwardAPI')) {
                obj['downwardAPI'] = PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI.constructFromObject(data['downwardAPI']);
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfSecret.constructFromObject(data['secret']);
            }
            if (data.hasOwnProperty('serviceAccountToken')) {
                obj['serviceAccountToken'] = PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfServiceAccountToken.constructFromObject(data['serviceAccountToken']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `clusterTrustBundle`
        if (data['clusterTrustBundle']) { // data not null
          PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfClusterTrustBundle.validateJSON(data['clusterTrustBundle']);
        }
        // validate the optional field `configMap`
        if (data['configMap']) { // data not null
          PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.validateJSON(data['configMap']);
        }
        // validate the optional field `downwardAPI`
        if (data['downwardAPI']) { // data not null
          PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI.validateJSON(data['downwardAPI']);
        }
        // validate the optional field `secret`
        if (data['secret']) { // data not null
          PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfSecret.validateJSON(data['secret']);
        }
        // validate the optional field `serviceAccountToken`
        if (data['serviceAccountToken']) { // data not null
          PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfServiceAccountToken.validateJSON(data['serviceAccountToken']);
        }

        return true;
    }


}



/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfClusterTrustBundle} clusterTrustBundle
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.prototype['clusterTrustBundle'] = undefined;

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap} configMap
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.prototype['configMap'] = undefined;

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI} downwardAPI
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.prototype['downwardAPI'] = undefined;

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfSecret} secret
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.prototype['secret'] = undefined;

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfServiceAccountToken} serviceAccountToken
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner.prototype['serviceAccountToken'] = undefined;






export default PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInner;

