/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfVolumesInnerAllOfPortworxVolume model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfPortworxVolume
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfPortworxVolume {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfPortworxVolume</code>.
     * portworxVolume represents a portworx volume attached and mounted on kubelets host machine. Deprecated: PortworxVolume is deprecated. All operations for the in-tree portworxVolume type are redirected to the pxd.portworx.com CSI driver when the CSIMigrationPortworx feature-gate is on.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfPortworxVolume
     * @param volumeID {String} volumeID uniquely identifies a Portworx volume
     */
    constructor(volumeID) { 
        
        PodSpecAllOfVolumesInnerAllOfPortworxVolume.initialize(this, volumeID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, volumeID) { 
        obj['volumeID'] = volumeID || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfPortworxVolume</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfPortworxVolume} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfPortworxVolume} The populated <code>PodSpecAllOfVolumesInnerAllOfPortworxVolume</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfPortworxVolume();

            if (data.hasOwnProperty('fsType')) {
                obj['fsType'] = ApiClient.convertToType(data['fsType'], 'String');
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('volumeID')) {
                obj['volumeID'] = ApiClient.convertToType(data['volumeID'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfPortworxVolume</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfPortworxVolume</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfVolumesInnerAllOfPortworxVolume.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fsType'] && !(typeof data['fsType'] === 'string' || data['fsType'] instanceof String)) {
            throw new Error("Expected the field `fsType` to be a primitive type in the JSON string but got " + data['fsType']);
        }
        // ensure the json data is a string
        if (data['volumeID'] && !(typeof data['volumeID'] === 'string' || data['volumeID'] instanceof String)) {
            throw new Error("Expected the field `volumeID` to be a primitive type in the JSON string but got " + data['volumeID']);
        }

        return true;
    }


}

PodSpecAllOfVolumesInnerAllOfPortworxVolume.RequiredProperties = ["volumeID"];

/**
 * fSType represents the filesystem type to mount Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\". Implicitly inferred to be \"ext4\" if unspecified.
 * @member {String} fsType
 */
PodSpecAllOfVolumesInnerAllOfPortworxVolume.prototype['fsType'] = undefined;

/**
 * readOnly defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
 * @member {Boolean} readOnly
 */
PodSpecAllOfVolumesInnerAllOfPortworxVolume.prototype['readOnly'] = undefined;

/**
 * volumeID uniquely identifies a Portworx volume
 * @member {String} volumeID
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfPortworxVolume.prototype['volumeID'] = '';






export default PodSpecAllOfVolumesInnerAllOfPortworxVolume;

