/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner model module.
 * @module model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner</code>.
     * @alias module:model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner
     * @param name {String} The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
     * @param value {String} The header field value
     */
    constructor(name, value) { 
        
        PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner.initialize(this, name, value);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, value) { 
        obj['name'] = name || '';
        obj['value'] = value || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner} The populated <code>PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['value'] && !(typeof data['value'] === 'string' || data['value'] instanceof String)) {
            throw new Error("Expected the field `value` to be a primitive type in the JSON string but got " + data['value']);
        }

        return true;
    }


}

PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner.RequiredProperties = ["name", "value"];

/**
 * The header field name. This will be canonicalized upon output, so case-variant names will be understood as the same header.
 * @member {String} name
 * @default ''
 */
PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner.prototype['name'] = '';

/**
 * The header field value
 * @member {String} value
 * @default ''
 */
PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner.prototype['value'] = '';






export default PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGetAllOfHttpHeadersInner;

