/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTermAllOfLabelSelectorAllOfMatchExpressionsInner from './PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTermAllOfLabelSelectorAllOfMatchExpressionsInner';

/**
 * The PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector model module.
 * @module model/PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector
 * @version 1.0.0
 */
class PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector {
    /**
     * Constructs a new <code>PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector</code>.
     * LabelSelector is used to find matching pods. Pods that match this label selector are counted to determine the number of pods in their corresponding topology domain.
     * @alias module:model/PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector
     */
    constructor() { 
        
        PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector} The populated <code>PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector();

            if (data.hasOwnProperty('matchExpressions')) {
                obj['matchExpressions'] = ApiClient.convertToType(data['matchExpressions'], [PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTermAllOfLabelSelectorAllOfMatchExpressionsInner]);
            }
            if (data.hasOwnProperty('matchLabels')) {
                obj['matchLabels'] = ApiClient.convertToType(data['matchLabels'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector</code>.
     */
    static validateJSON(data) {
        if (data['matchExpressions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matchExpressions'])) {
                throw new Error("Expected the field `matchExpressions` to be an array in the JSON data but got " + data['matchExpressions']);
            }
            // validate the optional field `matchExpressions` (array)
            for (const item of data['matchExpressions']) {
                PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTermAllOfLabelSelectorAllOfMatchExpressionsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * matchExpressions is a list of label selector requirements. The requirements are ANDed.
 * @member {Array.<module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTermAllOfLabelSelectorAllOfMatchExpressionsInner>} matchExpressions
 */
PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector.prototype['matchExpressions'] = undefined;

/**
 * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.
 * @member {Object.<String, String>} matchLabels
 */
PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector.prototype['matchLabels'] = undefined;






export default PodSpecAllOfTopologySpreadConstraintsInnerAllOfLabelSelector;

