/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner model module.
 * @module model/PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner</code>.
     * @alias module:model/PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner
     * @param name {String} Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
     */
    constructor(name) { 
        
        PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner} The populated <code>PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('request')) {
                obj['request'] = ApiClient.convertToType(data['request'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['request'] && !(typeof data['request'] === 'string' || data['request'] instanceof String)) {
            throw new Error("Expected the field `request` to be a primitive type in the JSON string but got " + data['request']);
        }

        return true;
    }


}

PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner.RequiredProperties = ["name"];

/**
 * Name must match the name of one entry in pod.spec.resourceClaims of the Pod where this field is used. It makes that resource available inside a container.
 * @member {String} name
 * @default ''
 */
PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner.prototype['name'] = '';

/**
 * Request is the name chosen for a request in the referenced claim. If empty, everything from the claim is made available, otherwise only the result of this request.
 * @member {String} request
 */
PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner.prototype['request'] = undefined;






export default PodSpecAllOfContainersInnerAllOfResourcesAllOfClaimsInner;

