/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities model module.
 * @module model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities</code>.
     * The capabilities to add/drop when running containers. Defaults to the default set of capabilities granted by the container runtime. Note that this field cannot be set when spec.os.name is windows.
     * @alias module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities
     */
    constructor() { 
        
        PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities} The populated <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities();

            if (data.hasOwnProperty('add')) {
                obj['add'] = ApiClient.convertToType(data['add'], ['String']);
            }
            if (data.hasOwnProperty('drop')) {
                obj['drop'] = ApiClient.convertToType(data['drop'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['add'])) {
            throw new Error("Expected the field `add` to be an array in the JSON data but got " + data['add']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['drop'])) {
            throw new Error("Expected the field `drop` to be an array in the JSON data but got " + data['drop']);
        }

        return true;
    }


}



/**
 * Added capabilities
 * @member {Array.<String>} add
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities.prototype['add'] = undefined;

/**
 * Removed capabilities
 * @member {Array.<String>} drop
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities.prototype['drop'] = undefined;






export default PodSpecAllOfContainersInnerAllOfSecurityContextAllOfCapabilities;

