/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfContainersInnerAllOfVolumeDevicesInner model module.
 * @module model/PodSpecAllOfContainersInnerAllOfVolumeDevicesInner
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfVolumeDevicesInner {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfVolumeDevicesInner</code>.
     * @alias module:model/PodSpecAllOfContainersInnerAllOfVolumeDevicesInner
     * @param devicePath {String} devicePath is the path inside of the container that the device will be mapped to.
     * @param name {String} name must match the name of a persistentVolumeClaim in the pod
     */
    constructor(devicePath, name) { 
        
        PodSpecAllOfContainersInnerAllOfVolumeDevicesInner.initialize(this, devicePath, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, devicePath, name) { 
        obj['devicePath'] = devicePath || '';
        obj['name'] = name || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfVolumeDevicesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfVolumeDevicesInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfVolumeDevicesInner} The populated <code>PodSpecAllOfContainersInnerAllOfVolumeDevicesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfVolumeDevicesInner();

            if (data.hasOwnProperty('devicePath')) {
                obj['devicePath'] = ApiClient.convertToType(data['devicePath'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfVolumeDevicesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfVolumeDevicesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfContainersInnerAllOfVolumeDevicesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['devicePath'] && !(typeof data['devicePath'] === 'string' || data['devicePath'] instanceof String)) {
            throw new Error("Expected the field `devicePath` to be a primitive type in the JSON string but got " + data['devicePath']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

PodSpecAllOfContainersInnerAllOfVolumeDevicesInner.RequiredProperties = ["devicePath", "name"];

/**
 * devicePath is the path inside of the container that the device will be mapped to.
 * @member {String} devicePath
 * @default ''
 */
PodSpecAllOfContainersInnerAllOfVolumeDevicesInner.prototype['devicePath'] = '';

/**
 * name must match the name of a persistentVolumeClaim in the pod
 * @member {String} name
 * @default ''
 */
PodSpecAllOfContainersInnerAllOfVolumeDevicesInner.prototype['name'] = '';






export default PodSpecAllOfContainersInnerAllOfVolumeDevicesInner;

