/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner from './PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner';

/**
 * The PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference model module.
 * @module model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference
 * @version 1.0.0
 */
class PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference {
    /**
     * Constructs a new <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference</code>.
     * A node selector term, associated with the corresponding weight.
     * @alias module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference
     */
    constructor() { 
        
        PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference} The populated <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference();

            if (data.hasOwnProperty('matchExpressions')) {
                obj['matchExpressions'] = ApiClient.convertToType(data['matchExpressions'], [PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner]);
            }
            if (data.hasOwnProperty('matchFields')) {
                obj['matchFields'] = ApiClient.convertToType(data['matchFields'], [PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference</code>.
     */
    static validateJSON(data) {
        if (data['matchExpressions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matchExpressions'])) {
                throw new Error("Expected the field `matchExpressions` to be an array in the JSON data but got " + data['matchExpressions']);
            }
            // validate the optional field `matchExpressions` (array)
            for (const item of data['matchExpressions']) {
                PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.validateJSON(item);
            };
        }
        if (data['matchFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matchFields'])) {
                throw new Error("Expected the field `matchFields` to be an array in the JSON data but got " + data['matchFields']);
            }
            // validate the optional field `matchFields` (array)
            for (const item of data['matchFields']) {
                PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of node selector requirements by node's labels.
 * @member {Array.<module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner>} matchExpressions
 */
PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference.prototype['matchExpressions'] = undefined;

/**
 * A list of node selector requirements by node's fields.
 * @member {Array.<module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner>} matchFields
 */
PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference.prototype['matchFields'] = undefined;






export default PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreference;

