/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner from './PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner';

/**
 * The PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI</code>.
     * downwardAPI information about the downwardAPI data to project
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI
     */
    constructor() { 
        
        PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI} The populated <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * Items is a list of DownwardAPIVolume file
 * @member {Array.<module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner>} items
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI.prototype['items'] = undefined;






export default PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfDownwardAPI;

