/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfVolumesInnerAllOfGitRepo model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfGitRepo
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfGitRepo {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfGitRepo</code>.
     * gitRepo represents a git repository at a particular revision. Deprecated: GitRepo is deprecated. To provision a container with a git repo, mount an EmptyDir into an InitContainer that clones the repo using git, then mount the EmptyDir into the Pod&#39;s container.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfGitRepo
     * @param repository {String} repository is the URL
     */
    constructor(repository) { 
        
        PodSpecAllOfVolumesInnerAllOfGitRepo.initialize(this, repository);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, repository) { 
        obj['repository'] = repository || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfGitRepo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfGitRepo} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfGitRepo} The populated <code>PodSpecAllOfVolumesInnerAllOfGitRepo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfGitRepo();

            if (data.hasOwnProperty('directory')) {
                obj['directory'] = ApiClient.convertToType(data['directory'], 'String');
            }
            if (data.hasOwnProperty('repository')) {
                obj['repository'] = ApiClient.convertToType(data['repository'], 'String');
            }
            if (data.hasOwnProperty('revision')) {
                obj['revision'] = ApiClient.convertToType(data['revision'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfGitRepo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfGitRepo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfVolumesInnerAllOfGitRepo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['directory'] && !(typeof data['directory'] === 'string' || data['directory'] instanceof String)) {
            throw new Error("Expected the field `directory` to be a primitive type in the JSON string but got " + data['directory']);
        }
        // ensure the json data is a string
        if (data['repository'] && !(typeof data['repository'] === 'string' || data['repository'] instanceof String)) {
            throw new Error("Expected the field `repository` to be a primitive type in the JSON string but got " + data['repository']);
        }
        // ensure the json data is a string
        if (data['revision'] && !(typeof data['revision'] === 'string' || data['revision'] instanceof String)) {
            throw new Error("Expected the field `revision` to be a primitive type in the JSON string but got " + data['revision']);
        }

        return true;
    }


}

PodSpecAllOfVolumesInnerAllOfGitRepo.RequiredProperties = ["repository"];

/**
 * directory is the target directory name. Must not contain or start with '..'.  If '.' is supplied, the volume directory will be the git repository.  Otherwise, if specified, the volume will contain the git repository in the subdirectory with the given name.
 * @member {String} directory
 */
PodSpecAllOfVolumesInnerAllOfGitRepo.prototype['directory'] = undefined;

/**
 * repository is the URL
 * @member {String} repository
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfGitRepo.prototype['repository'] = '';

/**
 * revision is the commit hash for the specified revision.
 * @member {String} revision
 */
PodSpecAllOfVolumesInnerAllOfGitRepo.prototype['revision'] = undefined;






export default PodSpecAllOfVolumesInnerAllOfGitRepo;

