/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner model module.
 * @module model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner
 * @version 1.0.0
 */
class PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner {
    /**
     * Constructs a new <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner</code>.
     * @alias module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner
     * @param key {String} The label key that the selector applies to.
     * @param operator {String} Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
     */
    constructor(key, operator) { 
        
        PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.initialize(this, key, operator);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key, operator) { 
        obj['key'] = key || '';
        obj['operator'] = operator || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner} The populated <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['values'])) {
            throw new Error("Expected the field `values` to be an array in the JSON data but got " + data['values']);
        }

        return true;
    }


}

PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.RequiredProperties = ["key", "operator"];

/**
 * The label key that the selector applies to.
 * @member {String} key
 * @default ''
 */
PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.prototype['key'] = '';

/**
 * Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
 * @member {String} operator
 * @default ''
 */
PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.prototype['operator'] = '';

/**
 * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
 * @member {Array.<String>} values
 */
PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner.prototype['values'] = undefined;






export default PodSpecAllOfAffinityAllOfNodeAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPreferenceAllOfMatchExpressionsInner;

