/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm from './PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm';

/**
 * The PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner model module.
 * @module model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner
 * @version 1.0.0
 */
class PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner {
    /**
     * Constructs a new <code>PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner</code>.
     * @alias module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner
     * @param podAffinityTerm {module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm} 
     * @param weight {Number} weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
     */
    constructor(podAffinityTerm, weight) { 
        
        PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner.initialize(this, podAffinityTerm, weight);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, podAffinityTerm, weight) { 
        obj['podAffinityTerm'] = podAffinityTerm;
        obj['weight'] = weight || 0;
    }

    /**
     * Constructs a <code>PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner} The populated <code>PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner();

            if (data.hasOwnProperty('podAffinityTerm')) {
                obj['podAffinityTerm'] = PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm.constructFromObject(data['podAffinityTerm']);
            }
            if (data.hasOwnProperty('weight')) {
                obj['weight'] = ApiClient.convertToType(data['weight'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `podAffinityTerm`
        if (data['podAffinityTerm']) { // data not null
          PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm.validateJSON(data['podAffinityTerm']);
        }

        return true;
    }


}

PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner.RequiredProperties = ["podAffinityTerm", "weight"];

/**
 * @member {module:model/PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInnerAllOfPodAffinityTerm} podAffinityTerm
 */
PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner.prototype['podAffinityTerm'] = undefined;

/**
 * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
 * @member {Number} weight
 * @default 0
 */
PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner.prototype['weight'] = 0;






export default PodSpecAllOfAffinityAllOfPodAffinityAllOfPreferredDuringSchedulingIgnoredDuringExecutionInner;

