/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning model module.
 * @module model/PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning
 * @version 1.0.0
 */
class PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning {
    /**
     * Constructs a new <code>PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning</code>.
     * Details about a running container
     * @alias module:model/PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning
     */
    constructor() { 
        
        PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning} obj Optional instance to populate.
     * @return {module:model/PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning} The populated <code>PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning();

            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @member {Date} startedAt
 */
PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning.prototype['startedAt'] = undefined;






export default PodStatusAllOfContainerStatusesInnerAllOfLastStateAllOfRunning;

