/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfVolumesInnerAllOfQuobyte model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfQuobyte
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfQuobyte {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfQuobyte</code>.
     * quobyte represents a Quobyte mount on the host that shares a pod&#39;s lifetime. Deprecated: Quobyte is deprecated and the in-tree quobyte type is no longer supported.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfQuobyte
     * @param registry {String} registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes
     * @param volume {String} volume is a string that references an already created Quobyte volume by name.
     */
    constructor(registry, volume) { 
        
        PodSpecAllOfVolumesInnerAllOfQuobyte.initialize(this, registry, volume);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, registry, volume) { 
        obj['registry'] = registry || '';
        obj['volume'] = volume || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfQuobyte</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfQuobyte} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfQuobyte} The populated <code>PodSpecAllOfVolumesInnerAllOfQuobyte</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfQuobyte();

            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('registry')) {
                obj['registry'] = ApiClient.convertToType(data['registry'], 'String');
            }
            if (data.hasOwnProperty('tenant')) {
                obj['tenant'] = ApiClient.convertToType(data['tenant'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('volume')) {
                obj['volume'] = ApiClient.convertToType(data['volume'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfQuobyte</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfQuobyte</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfVolumesInnerAllOfQuobyte.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['group'] && !(typeof data['group'] === 'string' || data['group'] instanceof String)) {
            throw new Error("Expected the field `group` to be a primitive type in the JSON string but got " + data['group']);
        }
        // ensure the json data is a string
        if (data['registry'] && !(typeof data['registry'] === 'string' || data['registry'] instanceof String)) {
            throw new Error("Expected the field `registry` to be a primitive type in the JSON string but got " + data['registry']);
        }
        // ensure the json data is a string
        if (data['tenant'] && !(typeof data['tenant'] === 'string' || data['tenant'] instanceof String)) {
            throw new Error("Expected the field `tenant` to be a primitive type in the JSON string but got " + data['tenant']);
        }
        // ensure the json data is a string
        if (data['user'] && !(typeof data['user'] === 'string' || data['user'] instanceof String)) {
            throw new Error("Expected the field `user` to be a primitive type in the JSON string but got " + data['user']);
        }
        // ensure the json data is a string
        if (data['volume'] && !(typeof data['volume'] === 'string' || data['volume'] instanceof String)) {
            throw new Error("Expected the field `volume` to be a primitive type in the JSON string but got " + data['volume']);
        }

        return true;
    }


}

PodSpecAllOfVolumesInnerAllOfQuobyte.RequiredProperties = ["registry", "volume"];

/**
 * group to map volume access to Default is no group
 * @member {String} group
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['group'] = undefined;

/**
 * readOnly here will force the Quobyte volume to be mounted with read-only permissions. Defaults to false.
 * @member {Boolean} readOnly
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['readOnly'] = undefined;

/**
 * registry represents a single or multiple Quobyte Registry services specified as a string as host:port pair (multiple entries are separated with commas) which acts as the central registry for volumes
 * @member {String} registry
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['registry'] = '';

/**
 * tenant owning the given Quobyte volume in the Backend Used with dynamically provisioned Quobyte volumes, value is set by the plugin
 * @member {String} tenant
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['tenant'] = undefined;

/**
 * user to map volume access to Defaults to serivceaccount user
 * @member {String} user
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['user'] = undefined;

/**
 * volume is a string that references an already created Quobyte volume by name.
 * @member {String} volume
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfQuobyte.prototype['volume'] = '';






export default PodSpecAllOfVolumesInnerAllOfQuobyte;

