/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef</code>.
     * secretRef is Optional: secretRef is reference to the secret object containing sensitive information to pass to the plugin scripts. This may be empty if no secret object is specified. If the secret object contains more than one secret, all secrets are passed to the plugin scripts.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef
     */
    constructor() { 
        
        PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['name'] = '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef} The populated <code>PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @member {String} name
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef.prototype['name'] = '';






export default PodSpecAllOfVolumesInnerAllOfFlexVolumeAllOfSecretRef;

