/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit</code>.
     * sizeLimit is the total amount of local storage required for this EmptyDir volume. The size limit is also applicable for memory medium. The maximum usage on memory medium EmptyDir would be the minimum value between the SizeLimit specified here and the sum of memory limits of all containers in a pod. The default is nil which means that the limit is undefined. More info: https://kubernetes.io/docs/concepts/storage/volumes#emptydir
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit
     */
    constructor() { 
        
        PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit} The populated <code>PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit();

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit</code>.
     */
    static validateJSON(data) {

        return true;
    }


}








export default PodSpecAllOfVolumesInnerAllOfEmptyDirAllOfSizeLimit;

