/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfFieldRef from './PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfFieldRef';
import PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfResourceFieldRef from './PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfResourceFieldRef';

/**
 * The PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner</code>.
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner
     * @param path {String} Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
     */
    constructor(path) { 
        
        PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.initialize(this, path);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, path) { 
        obj['path'] = path || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner} The populated <code>PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner();

            if (data.hasOwnProperty('fieldRef')) {
                obj['fieldRef'] = PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfFieldRef.constructFromObject(data['fieldRef']);
            }
            if (data.hasOwnProperty('mode')) {
                obj['mode'] = ApiClient.convertToType(data['mode'], 'Number');
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('resourceFieldRef')) {
                obj['resourceFieldRef'] = PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfResourceFieldRef.constructFromObject(data['resourceFieldRef']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `fieldRef`
        if (data['fieldRef']) { // data not null
          PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfFieldRef.validateJSON(data['fieldRef']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // validate the optional field `resourceFieldRef`
        if (data['resourceFieldRef']) { // data not null
          PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfResourceFieldRef.validateJSON(data['resourceFieldRef']);
        }

        return true;
    }


}

PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.RequiredProperties = ["path"];

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfFieldRef} fieldRef
 */
PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.prototype['fieldRef'] = undefined;

/**
 * Optional: mode bits used to set permissions on this file, must be an octal value between 0000 and 0777 or a decimal value between 0 and 511. YAML accepts both octal and decimal values, JSON requires decimal values for mode bits. If not specified, the volume defaultMode will be used. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.
 * @member {Number} mode
 */
PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.prototype['mode'] = undefined;

/**
 * Required: Path is  the relative path name of the file to be created. Must not be absolute or contain the '..' path. Must be utf-8 encoded. The first item of the relative path must not start with '..'
 * @member {String} path
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.prototype['path'] = '';

/**
 * @member {module:model/PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInnerAllOfResourceFieldRef} resourceFieldRef
 */
PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner.prototype['resourceFieldRef'] = undefined;






export default PodSpecAllOfVolumesInnerAllOfDownwardAPIAllOfItemsInner;

