/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions model module.
 * @module model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions</code>.
     * The Windows specific settings applied to all containers. If unspecified, the options from the PodSecurityContext will be used. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. Note that this field cannot be set when spec.os.name is linux.
     * @alias module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions
     */
    constructor() { 
        
        PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions} The populated <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions();

            if (data.hasOwnProperty('gmsaCredentialSpec')) {
                obj['gmsaCredentialSpec'] = ApiClient.convertToType(data['gmsaCredentialSpec'], 'String');
            }
            if (data.hasOwnProperty('gmsaCredentialSpecName')) {
                obj['gmsaCredentialSpecName'] = ApiClient.convertToType(data['gmsaCredentialSpecName'], 'String');
            }
            if (data.hasOwnProperty('hostProcess')) {
                obj['hostProcess'] = ApiClient.convertToType(data['hostProcess'], 'Boolean');
            }
            if (data.hasOwnProperty('runAsUserName')) {
                obj['runAsUserName'] = ApiClient.convertToType(data['runAsUserName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['gmsaCredentialSpec'] && !(typeof data['gmsaCredentialSpec'] === 'string' || data['gmsaCredentialSpec'] instanceof String)) {
            throw new Error("Expected the field `gmsaCredentialSpec` to be a primitive type in the JSON string but got " + data['gmsaCredentialSpec']);
        }
        // ensure the json data is a string
        if (data['gmsaCredentialSpecName'] && !(typeof data['gmsaCredentialSpecName'] === 'string' || data['gmsaCredentialSpecName'] instanceof String)) {
            throw new Error("Expected the field `gmsaCredentialSpecName` to be a primitive type in the JSON string but got " + data['gmsaCredentialSpecName']);
        }
        // ensure the json data is a string
        if (data['runAsUserName'] && !(typeof data['runAsUserName'] === 'string' || data['runAsUserName'] instanceof String)) {
            throw new Error("Expected the field `runAsUserName` to be a primitive type in the JSON string but got " + data['runAsUserName']);
        }

        return true;
    }


}



/**
 * GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
 * @member {String} gmsaCredentialSpec
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions.prototype['gmsaCredentialSpec'] = undefined;

/**
 * GMSACredentialSpecName is the name of the GMSA credential spec to use.
 * @member {String} gmsaCredentialSpecName
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions.prototype['gmsaCredentialSpecName'] = undefined;

/**
 * HostProcess determines if a container should be run as a 'Host Process' container. All of a Pod's containers must have the same effective HostProcess value (it is not allowed to have a mix of HostProcess containers and non-HostProcess containers). In addition, if HostProcess is true then HostNetwork must also be set to true.
 * @member {Boolean} hostProcess
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions.prototype['hostProcess'] = undefined;

/**
 * The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
 * @member {String} runAsUserName
 */
PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions.prototype['runAsUserName'] = undefined;






export default PodSpecAllOfContainersInnerAllOfSecurityContextAllOfWindowsOptions;

