/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfExec from './PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfExec';
import PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGet from './PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGet';
import PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfGrpc from './PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfGrpc';
import PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfTcpSocket from './PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfTcpSocket';

/**
 * The PodSpecAllOfContainersInnerAllOfStartupProbe model module.
 * @module model/PodSpecAllOfContainersInnerAllOfStartupProbe
 * @version 1.0.0
 */
class PodSpecAllOfContainersInnerAllOfStartupProbe {
    /**
     * Constructs a new <code>PodSpecAllOfContainersInnerAllOfStartupProbe</code>.
     * StartupProbe indicates that the Pod has successfully initialized. If specified, no other probes are executed until this completes successfully. If this probe fails, the Pod will be restarted, just as if the livenessProbe failed. This can be used to provide different probe parameters at the beginning of a Pod&#39;s lifecycle, when it might take a long time to load data or warm a cache, than during steady-state operation. This cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
     * @alias module:model/PodSpecAllOfContainersInnerAllOfStartupProbe
     */
    constructor() { 
        
        PodSpecAllOfContainersInnerAllOfStartupProbe.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PodSpecAllOfContainersInnerAllOfStartupProbe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfContainersInnerAllOfStartupProbe} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfContainersInnerAllOfStartupProbe} The populated <code>PodSpecAllOfContainersInnerAllOfStartupProbe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfContainersInnerAllOfStartupProbe();

            if (data.hasOwnProperty('exec')) {
                obj['exec'] = PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfExec.constructFromObject(data['exec']);
            }
            if (data.hasOwnProperty('failureThreshold')) {
                obj['failureThreshold'] = ApiClient.convertToType(data['failureThreshold'], 'Number');
            }
            if (data.hasOwnProperty('grpc')) {
                obj['grpc'] = PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfGrpc.constructFromObject(data['grpc']);
            }
            if (data.hasOwnProperty('httpGet')) {
                obj['httpGet'] = PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGet.constructFromObject(data['httpGet']);
            }
            if (data.hasOwnProperty('initialDelaySeconds')) {
                obj['initialDelaySeconds'] = ApiClient.convertToType(data['initialDelaySeconds'], 'Number');
            }
            if (data.hasOwnProperty('periodSeconds')) {
                obj['periodSeconds'] = ApiClient.convertToType(data['periodSeconds'], 'Number');
            }
            if (data.hasOwnProperty('successThreshold')) {
                obj['successThreshold'] = ApiClient.convertToType(data['successThreshold'], 'Number');
            }
            if (data.hasOwnProperty('tcpSocket')) {
                obj['tcpSocket'] = PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfTcpSocket.constructFromObject(data['tcpSocket']);
            }
            if (data.hasOwnProperty('terminationGracePeriodSeconds')) {
                obj['terminationGracePeriodSeconds'] = ApiClient.convertToType(data['terminationGracePeriodSeconds'], 'Number');
            }
            if (data.hasOwnProperty('timeoutSeconds')) {
                obj['timeoutSeconds'] = ApiClient.convertToType(data['timeoutSeconds'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfContainersInnerAllOfStartupProbe</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfContainersInnerAllOfStartupProbe</code>.
     */
    static validateJSON(data) {
        // validate the optional field `exec`
        if (data['exec']) { // data not null
          PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfExec.validateJSON(data['exec']);
        }
        // validate the optional field `grpc`
        if (data['grpc']) { // data not null
          PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfGrpc.validateJSON(data['grpc']);
        }
        // validate the optional field `httpGet`
        if (data['httpGet']) { // data not null
          PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGet.validateJSON(data['httpGet']);
        }
        // validate the optional field `tcpSocket`
        if (data['tcpSocket']) { // data not null
          PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfTcpSocket.validateJSON(data['tcpSocket']);
        }

        return true;
    }


}



/**
 * @member {module:model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfExec} exec
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['exec'] = undefined;

/**
 * Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
 * @member {Number} failureThreshold
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['failureThreshold'] = undefined;

/**
 * @member {module:model/PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfGrpc} grpc
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['grpc'] = undefined;

/**
 * @member {module:model/PodSpecAllOfContainersInnerAllOfLifecycleAllOfPostStartAllOfHttpGet} httpGet
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['httpGet'] = undefined;

/**
 * Number of seconds after the container has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
 * @member {Number} initialDelaySeconds
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['initialDelaySeconds'] = undefined;

/**
 * How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
 * @member {Number} periodSeconds
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['periodSeconds'] = undefined;

/**
 * Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
 * @member {Number} successThreshold
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['successThreshold'] = undefined;

/**
 * @member {module:model/PodSpecAllOfContainersInnerAllOfLivenessProbeAllOfTcpSocket} tcpSocket
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['tcpSocket'] = undefined;

/**
 * Optional duration in seconds the pod needs to terminate gracefully upon probe failure. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. If this value is nil, the pod's terminationGracePeriodSeconds will be used. Otherwise, this value overrides the value provided by the pod spec. Value must be non-negative integer. The value zero indicates stop immediately via the kill signal (no opportunity to shut down). This is a beta field and requires enabling ProbeTerminationGracePeriod feature gate. Minimum value is 1. spec.terminationGracePeriodSeconds is used if unset.
 * @member {Number} terminationGracePeriodSeconds
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['terminationGracePeriodSeconds'] = undefined;

/**
 * Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
 * @member {Number} timeoutSeconds
 */
PodSpecAllOfContainersInnerAllOfStartupProbe.prototype['timeoutSeconds'] = undefined;






export default PodSpecAllOfContainersInnerAllOfStartupProbe;

