/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PodSpecAllOfVolumesInnerAllOfConfigMapAllOfItemsInner from './PodSpecAllOfVolumesInnerAllOfConfigMapAllOfItemsInner';

/**
 * The PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap model module.
 * @module model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap
 * @version 1.0.0
 */
class PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap {
    /**
     * Constructs a new <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap</code>.
     * configMap information about the configMap data to project
     * @alias module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap
     */
    constructor() { 
        
        PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['name'] = '';
    }

    /**
     * Constructs a <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap} The populated <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [PodSpecAllOfVolumesInnerAllOfConfigMapAllOfItemsInner]);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('optional')) {
                obj['optional'] = ApiClient.convertToType(data['optional'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap</code>.
     */
    static validateJSON(data) {
        if (data['items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items'])) {
                throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
            }
            // validate the optional field `items` (array)
            for (const item of data['items']) {
                PodSpecAllOfVolumesInnerAllOfConfigMapAllOfItemsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * items if unspecified, each key-value pair in the Data field of the referenced ConfigMap will be projected into the volume as a file whose name is the key and content is the value. If specified, the listed keys will be projected into the specified paths, and unlisted keys will not be present. If a key is specified which is not present in the ConfigMap, the volume setup will error unless it is marked optional. Paths must be relative and may not contain the '..' path or start with '..'.
 * @member {Array.<module:model/PodSpecAllOfVolumesInnerAllOfConfigMapAllOfItemsInner>} items
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.prototype['items'] = undefined;

/**
 * Name of the referent. This field is effectively required, but due to backwards compatibility is allowed to be empty. Instances of this type with an empty value here are almost certainly wrong. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
 * @member {String} name
 * @default ''
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.prototype['name'] = '';

/**
 * optional specify whether the ConfigMap or its keys must be defined
 * @member {Boolean} optional
 */
PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap.prototype['optional'] = undefined;






export default PodSpecAllOfVolumesInnerAllOfProjectedAllOfSourcesInnerAllOfConfigMap;

