/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PodSpecAllOfResourceClaimsInner model module.
 * @module model/PodSpecAllOfResourceClaimsInner
 * @version 1.0.0
 */
class PodSpecAllOfResourceClaimsInner {
    /**
     * Constructs a new <code>PodSpecAllOfResourceClaimsInner</code>.
     * @alias module:model/PodSpecAllOfResourceClaimsInner
     * @param name {String} Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL.
     */
    constructor(name) { 
        
        PodSpecAllOfResourceClaimsInner.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name || '';
    }

    /**
     * Constructs a <code>PodSpecAllOfResourceClaimsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PodSpecAllOfResourceClaimsInner} obj Optional instance to populate.
     * @return {module:model/PodSpecAllOfResourceClaimsInner} The populated <code>PodSpecAllOfResourceClaimsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PodSpecAllOfResourceClaimsInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resourceClaimName')) {
                obj['resourceClaimName'] = ApiClient.convertToType(data['resourceClaimName'], 'String');
            }
            if (data.hasOwnProperty('resourceClaimTemplateName')) {
                obj['resourceClaimTemplateName'] = ApiClient.convertToType(data['resourceClaimTemplateName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PodSpecAllOfResourceClaimsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PodSpecAllOfResourceClaimsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PodSpecAllOfResourceClaimsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['resourceClaimName'] && !(typeof data['resourceClaimName'] === 'string' || data['resourceClaimName'] instanceof String)) {
            throw new Error("Expected the field `resourceClaimName` to be a primitive type in the JSON string but got " + data['resourceClaimName']);
        }
        // ensure the json data is a string
        if (data['resourceClaimTemplateName'] && !(typeof data['resourceClaimTemplateName'] === 'string' || data['resourceClaimTemplateName'] instanceof String)) {
            throw new Error("Expected the field `resourceClaimTemplateName` to be a primitive type in the JSON string but got " + data['resourceClaimTemplateName']);
        }

        return true;
    }


}

PodSpecAllOfResourceClaimsInner.RequiredProperties = ["name"];

/**
 * Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL.
 * @member {String} name
 * @default ''
 */
PodSpecAllOfResourceClaimsInner.prototype['name'] = '';

/**
 * ResourceClaimName is the name of a ResourceClaim object in the same namespace as this pod.  Exactly one of ResourceClaimName and ResourceClaimTemplateName must be set.
 * @member {String} resourceClaimName
 */
PodSpecAllOfResourceClaimsInner.prototype['resourceClaimName'] = undefined;

/**
 * ResourceClaimTemplateName is the name of a ResourceClaimTemplate object in the same namespace as this pod.  The template will be used to create a new ResourceClaim, which will be bound to this pod. When this pod is deleted, the ResourceClaim will also be deleted. The pod name and resource name, along with a generated component, will be used to form a unique name for the ResourceClaim, which will be recorded in pod.status.resourceClaimStatuses.  This field is immutable and no changes will be made to the corresponding ResourceClaim by the control plane after creating the ResourceClaim.  Exactly one of ResourceClaimName and ResourceClaimTemplateName must be set.
 * @member {String} resourceClaimTemplateName
 */
PodSpecAllOfResourceClaimsInner.prototype['resourceClaimTemplateName'] = undefined;






export default PodSpecAllOfResourceClaimsInner;

