/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.K8SResourceApi);
  }
}(this, function(expect, K8SResourceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new K8SResourceApi.PodSpec();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PodSpec', function() {
    it('should create an instance of PodSpec', function() {
      // uncomment below and update the code to test PodSpec
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be.a(K8SResourceApi.PodSpec);
    });

    it('should have the property activeDeadlineSeconds (base name: "activeDeadlineSeconds")', function() {
      // uncomment below and update the code to test the property activeDeadlineSeconds
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property affinity (base name: "affinity")', function() {
      // uncomment below and update the code to test the property affinity
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property automountServiceAccountToken (base name: "automountServiceAccountToken")', function() {
      // uncomment below and update the code to test the property automountServiceAccountToken
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property containers (base name: "containers")', function() {
      // uncomment below and update the code to test the property containers
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property dnsConfig (base name: "dnsConfig")', function() {
      // uncomment below and update the code to test the property dnsConfig
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property dnsPolicy (base name: "dnsPolicy")', function() {
      // uncomment below and update the code to test the property dnsPolicy
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property enableServiceLinks (base name: "enableServiceLinks")', function() {
      // uncomment below and update the code to test the property enableServiceLinks
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property ephemeralContainers (base name: "ephemeralContainers")', function() {
      // uncomment below and update the code to test the property ephemeralContainers
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostAliases (base name: "hostAliases")', function() {
      // uncomment below and update the code to test the property hostAliases
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostIPC (base name: "hostIPC")', function() {
      // uncomment below and update the code to test the property hostIPC
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostNetwork (base name: "hostNetwork")', function() {
      // uncomment below and update the code to test the property hostNetwork
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostPID (base name: "hostPID")', function() {
      // uncomment below and update the code to test the property hostPID
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostUsers (base name: "hostUsers")', function() {
      // uncomment below and update the code to test the property hostUsers
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property hostname (base name: "hostname")', function() {
      // uncomment below and update the code to test the property hostname
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property imagePullSecrets (base name: "imagePullSecrets")', function() {
      // uncomment below and update the code to test the property imagePullSecrets
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property initContainers (base name: "initContainers")', function() {
      // uncomment below and update the code to test the property initContainers
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property nodeName (base name: "nodeName")', function() {
      // uncomment below and update the code to test the property nodeName
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property nodeSelector (base name: "nodeSelector")', function() {
      // uncomment below and update the code to test the property nodeSelector
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property os (base name: "os")', function() {
      // uncomment below and update the code to test the property os
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property overhead (base name: "overhead")', function() {
      // uncomment below and update the code to test the property overhead
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property preemptionPolicy (base name: "preemptionPolicy")', function() {
      // uncomment below and update the code to test the property preemptionPolicy
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property priorityClassName (base name: "priorityClassName")', function() {
      // uncomment below and update the code to test the property priorityClassName
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property readinessGates (base name: "readinessGates")', function() {
      // uncomment below and update the code to test the property readinessGates
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property resourceClaims (base name: "resourceClaims")', function() {
      // uncomment below and update the code to test the property resourceClaims
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property resources (base name: "resources")', function() {
      // uncomment below and update the code to test the property resources
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property restartPolicy (base name: "restartPolicy")', function() {
      // uncomment below and update the code to test the property restartPolicy
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property runtimeClassName (base name: "runtimeClassName")', function() {
      // uncomment below and update the code to test the property runtimeClassName
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property schedulerName (base name: "schedulerName")', function() {
      // uncomment below and update the code to test the property schedulerName
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property schedulingGates (base name: "schedulingGates")', function() {
      // uncomment below and update the code to test the property schedulingGates
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property securityContext (base name: "securityContext")', function() {
      // uncomment below and update the code to test the property securityContext
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property serviceAccount (base name: "serviceAccount")', function() {
      // uncomment below and update the code to test the property serviceAccount
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property serviceAccountName (base name: "serviceAccountName")', function() {
      // uncomment below and update the code to test the property serviceAccountName
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property setHostnameAsFQDN (base name: "setHostnameAsFQDN")', function() {
      // uncomment below and update the code to test the property setHostnameAsFQDN
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property shareProcessNamespace (base name: "shareProcessNamespace")', function() {
      // uncomment below and update the code to test the property shareProcessNamespace
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property subdomain (base name: "subdomain")', function() {
      // uncomment below and update the code to test the property subdomain
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property terminationGracePeriodSeconds (base name: "terminationGracePeriodSeconds")', function() {
      // uncomment below and update the code to test the property terminationGracePeriodSeconds
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property tolerations (base name: "tolerations")', function() {
      // uncomment below and update the code to test the property tolerations
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property topologySpreadConstraints (base name: "topologySpreadConstraints")', function() {
      // uncomment below and update the code to test the property topologySpreadConstraints
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

    it('should have the property volumes (base name: "volumes")', function() {
      // uncomment below and update the code to test the property volumes
      //var instance = new K8SResourceApi.PodSpec();
      //expect(instance).to.be();
    });

  });

}));
