/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.K8SResourceApi);
  }
}(this, function(expect, K8SResourceApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PodSpecAllOfEphemeralContainersInnerAllOfLifecycle', function() {
    it('should create an instance of PodSpecAllOfEphemeralContainersInnerAllOfLifecycle', function() {
      // uncomment below and update the code to test PodSpecAllOfEphemeralContainersInnerAllOfLifecycle
      //var instance = new K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle();
      //expect(instance).to.be.a(K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle);
    });

    it('should have the property postStart (base name: "postStart")', function() {
      // uncomment below and update the code to test the property postStart
      //var instance = new K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle();
      //expect(instance).to.be();
    });

    it('should have the property preStop (base name: "preStop")', function() {
      // uncomment below and update the code to test the property preStop
      //var instance = new K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle();
      //expect(instance).to.be();
    });

    it('should have the property stopSignal (base name: "stopSignal")', function() {
      // uncomment below and update the code to test the property stopSignal
      //var instance = new K8SResourceApi.PodSpecAllOfEphemeralContainersInnerAllOfLifecycle();
      //expect(instance).to.be();
    });

  });

}));
