/**
 * K8S Resource API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetResource200Response from '../model/GetResource200Response';
import ResourceRequest from '../model/ResourceRequest';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getResource operation.
     * @callback module:api/DefaultApi~getResourceCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetResource200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 根据 GVK + namespace + name 获取对应的 K8s 资源
     * @param {module:model/ResourceRequest} resourceRequest 
     * @param {module:api/DefaultApi~getResourceCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetResource200Response}
     */
    getResource(resourceRequest, callback) {
      let postBody = resourceRequest;
      // verify the required parameter 'resourceRequest' is set
      if (resourceRequest === undefined || resourceRequest === null) {
        throw new Error("Missing the required parameter 'resourceRequest' when calling getResource");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = GetResource200Response;
      return this.apiClient.callApi(
        '/resource', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
