// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

// Defines values for UserNameActionRequestAction.
const (
	Create UserNameActionRequestAction = "create"
	Delete UserNameActionRequestAction = "delete"
	Get    UserNameActionRequestAction = "get"
	Put    UserNameActionRequestAction = "put"
)

// User defines model for User.
type User struct {
	// Balance 存款数
	Balance int32 `json:"balance"`

	// Name 用户名
	Name string `json:"name"`
}

// UserName defines model for UserName.
type UserName struct {
	// Name 用户名
	Name string `json:"name"`
}

// UserNameActionRequest defines model for UserNameActionRequest.
type UserNameActionRequest struct {
	// Action 操作类型，只能为 get/put/delete
	Action UserNameActionRequestAction `json:"action"`
	User   UserName                    `json:"user"`
}

// UserNameActionRequestAction 操作类型，只能为 get/put/delete
type UserNameActionRequestAction string

// UserActionsJSONRequestBody defines body for UserActions for application/json ContentType.
type UserActionsJSONRequestBody = UserNameActionRequest
