openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
security: []
servers: 
  - url: http://play:2000 
paths:
  /user:
    post:
      operationId: UserActions
      summary: 用户操作
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserNameActionRequest'
      responses:
        '200':
          description: 操作成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: 未找到
components:
  schemas:
    UserNameActionRequest:
      type: object
      required:
        - action
        - user
      properties:
        action:
          type: string
          enum: [create, get, put, delete]
          description: 操作类型，只能为 get/put/delete
        user:
          $ref: '#/components/schemas/UserName'
    User:
      $ref: './schema/user.yaml'
    UserName:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: 用户名